### ISSUE TITLE
0.2.6 Goal collision issues

### ISSUE THREAD

**Issue by Fooman1** [supraball/issues#56] opened 2014-05-27 00:44 UTC
In Pitch_walls:  As the red goalkeeper, I was able to get into the net area on the left side of the goal, facing the goal.  I could not replicate on the blue side.  I could not replicate in Hall, either side. 

Goalkeeper collision near the posts is a little strange.  I tried dodging straight into each post at different angles and there were times I thought the post would direct to one side, but I actually went to the other side.  I know we don't want keepers able to dodge flush with the wall, but please check to see that the post collisions are uniform and give the desired collision effect.

**Comment by Timoses** [comment] 2014-05-27 08:07
![image](https://cloud.githubusercontent.com/assets/6923843/3088799/21175d2e-e576-11e3-9218-c36ba872d907.png)

Got it 4 times now. Always on the left side of the red goal in db-pitch_walls.

**Comment by Seikah** [comment] 2014-06-19 16:38
If entering the goal on the left side was fixed in 2.7 by moving the blockage to the left, it overshot, because you can now enter from the right side. The easiest way to reproduce it is to stick to the right goal post as you sneak around it.

**Comment by Marenz** [comment] 2014-08-18 14:03
Assuming this is fixed by now, reopen if not

**Closed as completed by Marenz** 2014-08-18 14:03 UTC
Labels: bug, confirmed, reviewed
